### ISSUE TITLE
Support for LayerCAM

### ISSUE THREAD

**Issue by PengtaoJiang** [utkuozbulak/pytorch-cnn-visualizations#101]
Hi, @utkuozbulak, 
    Our paper "LayerCAM: Exploring Hierarchical Class Activation Maps for Localization" is accepted by TIP recently, which can visualize the class activation maps from any cnn layer of an off-the-shelf network.  Could you add our method to your popular repository for more people to try this method?   Our method is a simple modification of Grad-CAM. It should easy to implement.  Here is the [paper](http://mmcheng.net/mftp/Papers/21TIP_LayerCAM.pdf) and [code](https://github.com/PengtaoJiang/LayerCAM). Hope for your reply.

**Comment by utkuozbulak** [comment]
Hey, feel free to send a PR!

**Comment by PengtaoJiang** [comment]
Thanks a lot!

**Comment by PengtaoJiang** [comment]
@utkuozbulak  I have sent you a PR! Feel free to check it.

**Comment by utkuozbulak** [comment]
Yeah, will have a look as soon as there is spare time. Thanks for the PR.
