### ISSUE TITLE
How to get the sampling points with deformable conv?

### ISSUE THREAD

**Issue by kirkzZ** [utkuozbulak/pytorch-cnn-visualizations#104]
![image](https://user-images.githubusercontent.com/62935695/141613643-a290297b-c477-48a2-9223-e70e21db9aa1.png)
![image](https://user-images.githubusercontent.com/62935695/141613648-4778b5d4-25a6-4d0f-8e56-5c3cb549cd18.png)

**Comment by utkuozbulak** [comment]
Read the paper: Deformable Convolutional Networks?
