### ISSUE TITLE
why use np.ones instead of np.zeros, since you want to create some empty arrays

### ISSUE THREAD

**Issue by zhenni** [utkuozbulak/pytorch-cnn-visualizations#11]
https://github.com/utkuozbulak/pytorch-cnn-visualizations/blob/93d112c563e5e601eebab0eb7bf58bf9df30c008/src/gradcam.py#L81

**Comment by zhenni** [comment]
@utkuozbulak 
Thanks! I think it is clear.
I think the colormap `JET` is much better for visualization of heatmaps, instead of `HSV`. (`HSV` has red color for the smallest values and largest values as well.) If you choose `JET`, the color should not have the irritating red things.

**Comment by utkuozbulak** [comment]
Thanks for the advice! I will have a look at it!
