### ISSUE TITLE
Could you please provide the feature importance included dataset that has been generated?

### ISSUE THREAD

**Issue by bosaiiasliu** [utkuozbulak/pytorch-cnn-visualizations#110]
I found that using some methods like CAM to generate feature importance interpretations is slow, taking about 2 seconds for one image. If I want to generate all the image explanations in the Imagenet dataset, the time it takes seems very long. Or, is there a suitable acceleration method?

**Comment by utkuozbulak** [comment]
This is intended. The code is designed to work in cpu not cuda (so that it runs for everyone, even those who do not have a dedicated gpu). You should convert the parts that work on cpu to work on gpu to accelerate the speed.
