### ISSUE TITLE
Can this tool be used on non-classification tasks

### ISSUE THREAD

**Issue by sdu-huanhq** [utkuozbulak/pytorch-cnn-visualizations#119]
Hello,
First of all, thank you for your excellent work. But I have a question: Can I use this tool to simply observe intermediate features (i.e. which part of the network pays more attention to), and neural networks are not used for tasks related to classification (such as image classification, semantic segmentation, etc.)?
Looking forward to your replay.
Best wishes!

**Comment by utkuozbulak** [comment]
You could make some of the techniques work for types of problems out of classification but I'm not sure if what you observe will be meaningful.
