### ISSUE TITLE
Code application related issues

### ISSUE THREAD

**Issue by pake001** [utkuozbulak/pytorch-cnn-visualizations#120]
Hello,
First of all, thank you for your excellent work. 
 I have a question: If I were to use my own image data, please advise on what needs to be changed, thank you!
Looking forward to your replay.
Best wishes! #

**Comment by utkuozbulak** [comment]
Pretty much nothing. Use your image data with their respective class (on ImageNet).

**Comment by pake001** [comment]
> Pretty much nothing. Use your image data with their respective classes (on ImageNet).

I see. Thank you for your reply .
Duplicate of #
