### ISSUE TITLE
how to explain some operations in gradcam.py

### ISSUE THREAD

**Issue by miaowu16** [utkuozbulak/pytorch-cnn-visualizations#14]
**cam = np.ones(target.shape[1:], dtype=np.float32)**   why not creat a array whose values are zeros
for i, w in enumerate(weights):
    cam += w * target[i, :, :]
cam = cv2.resize(cam, (224, 224))
**cam = np.maximum(cam, 0)**    why do this operation

**Comment by miaowu16** [comment]
@utkuozbulak 
Thank you！I got it, and I have solved some other questions by reading the original paper.

**Comment by utkuozbulak** [comment]
Great!
