### ISSUE TITLE
3D inputs

### ISSUE THREAD

**Issue by CanPhi** [utkuozbulak/pytorch-cnn-visualizations#17]
Hi, 

thanks for your work, it looks very comprehensive and concise. I was wondering whether this code would also out-of-the-box work for 3D input data. 

It would be very useful to apply this to tomographic medical data, analogously as in the ChexNet paper:
https://stanfordmlgroup.github.io/projects/chexnet/img/chest-cam.png

Thanks!
Philippe

**Comment by utkuozbulak** [comment]
Hello,

Sure, you can apply these techniques to 3-D data. In fact, the images are already 3-D depending on how you look at it (Depth x Height x Width). I think you might need to modify the gradient acquisition and the visualization part a bit but overall, it should work.

**Comment by CanPhi** [comment]
Great, thanks! I will only have time to get into that in a couple of weeks probably but that s good to know!

**Comment by utkuozbulak** [comment]
Good luck with your task!
