### ISSUE TITLE
the processed image is not changed

### ISSUE THREAD

**Issue by buaaswf** [utkuozbulak/pytorch-cnn-visualizations#19]
Hi @utkuozbulak , I have change the input into a single RGB image. However, I found this line would output the original image without any changes.
https://github.com/utkuozbulak/pytorch-cnn-visualizations/blob/bcd8726f46457b269d2723d1cd991ae10927ef28/src/cnn_layer_visualization.py#L71

**Comment by buaaswf** [comment]
I wonder why this input is self.processed_image, it seems that it has nothing to do with the iteration

**Comment by utkuozbulak** [comment]
Optimizer is optimizing self.processed_image and at each iteration it updates this image. Howcome it has nothing to do with the iteration?

```python
optimizer = Adam([self.processed_image], lr=0.1, weight_decay=1e-6)
for i in range(1, x):
    optimizer.zero_grad()
    ...
    loss = -torch.mean(self.conv_output)
    loss.backward()
    optimizer.step()
    ...
```
