### ISSUE TITLE
Sharp edges in layer visualization 

### ISSUE THREAD

**Issue by McLawrence** [utkuozbulak/pytorch-cnn-visualizations#22]
This is probably not an issue with your code as it does not happen for your examples:

When doing activation maximization, the right and bottom rim of the generated image has a sharp edge, were the image grey:
![test_edge](https://user-images.githubusercontent.com/25885486/43540500-32d7d988-95c8-11e8-8667-dd99346ec2fe.jpg)

Do you have any idea why this jump occurs? Is this a problem with the model I am using or with the activation maximization itself?

**Comment by utkuozbulak** [comment]
Hey,

I vaguely remember coming across the same type of results but I can't recall why and/or how I fixed it (or even if I did fix it). Sorry for not being of help on this issue.
