### ISSUE TITLE
Other Contribution Method

### ISSUE THREAD

**Issue by muzi-8** [utkuozbulak/pytorch-cnn-visualizations#23]
I think the method “Integrated Gradients” and “LRP(Layer-relevance-propagation )”are
also popular. So, maybe these method can be implemented by pytorch framework.

**Comment by utkuozbulak** [comment]
Hey, I have seen that paper passing by and I wanna implement new things (also that paper) but currently have no time to do it. If you send a PR, it is more than welcome.

**Comment by utkuozbulak** [comment]
Well, it only took a year to implement 'integrated gradients'. I will see what I can do for LRP soon.
