### ISSUE TITLE
Segmentation fault (core dumped) with gradcam

### ISSUE THREAD

**Issue by nessieyang** [utkuozbulak/pytorch-cnn-visualizations#24]
Hi 
I am using the file gradcam.py to visualize my own network.
However when I begin to run it , it shows 'Segmentation fault (core dumped)'.
I can't locate the problem.
Can you help me to solve it?
Thanks a lot!

**Comment by utkuozbulak** [comment]
Hey, I don't get any errors with the code. Can you check your torch version? (pip show torch) It should be 0.4.0 +

**Comment by nessieyang** [comment]
> Hey, I don't get any errors with the code. Can you check your torch version? (pip show torch) It should be 0.4.0 +

Hi I have solved the problem. I think my torch version is okay. But the problem occurs at the file 'misc_functions.py'. It's an import problem. I just delete the line' from misc_functions import get_params, save_class_activation_on_image' from 'gradcam.py' and copy these functions to 'gradcam.py' and the code can run.

**Comment by utkuozbulak** [comment]
Great news!
