### ISSUE TITLE
Visualization with my custom model

### ISSUE THREAD

**Issue by munziliashali** [utkuozbulak/pytorch-cnn-visualizations#27]
Dear @utkuozbulak ,

I have my own custom model that looks like this:
input image --> torch.Size([1, 3, 34, 694])
cnn.conv0.weight torch.Size([64, 1, 3, 3])
cnn.conv0.bias torch.Size([64])
cnn.conv1.weight torch.Size([64, 64, 3, 3])
cnn.conv1.bias torch.Size([64])
etc etc

I tried to run the vanilla back prop code, however I got this error:
`RuntimeError: Given groups=1, weight[64, 1, 3, 3], so expected input[1, 3, 34, 694] to have 1 channels, but got 3 channels instead`

Do you have an idea where it might go wrong?

Thank you

**Comment by 1453042287** [comment]
i guess the format of the input is channel first so your input image is a RGB image with three channels but your first conv layer's in-channel require 3, so it's incompatible here
