### ISSUE TITLE
'gradcam.py' still needs cv2

### ISSUE THREAD

**Issue by CaesarPan** [utkuozbulak/pytorch-cnn-visualizations#35]
There's still `import cv2` in `gradcam.py` and `cv2.resize()` is called in that file.

**Comment by utkuozbulak** [comment]
Updated with https://github.com/utkuozbulak/pytorch-cnn-visualizations/commit/818b177b0d10394c1fd1c75465ff55aabadb221b in a very ugly way that makes me super unhappy. I think I will go over the way I handled PIL image/numpy matrix data types. It looks quite messy now.

Thanks for pointing it out!
