### ISSUE TITLE
how to see saliency maps from middle layers

### ISSUE THREAD

**Issue by YOONAHLEE** [utkuozbulak/pytorch-cnn-visualizations#37]
Hi, 

Do you know how to get neuron's saliency map from the middle layer?
I want to pick some neurons from the middle layer and compare visualization result
but I cannot figure out how to pick values to see an image from lots of gradients.

Thank you,

**Comment by utkuozbulak** [comment]
Hey,

Just do forward pass until the layer you want to visualize and perform gbp or vbp sourced from there.

**Comment by utkuozbulak** [comment]
Hey,

Check layer visualization file, you just modify the input image and forward pass again.
