### ISSUE TITLE
Getting Runtime Error

### ISSUE THREAD

**Issue by krushi1992** [utkuozbulak/pytorch-cnn-visualizations#45]
I am getting following error while testing the code with my own image. Could anyone please help me with that?

RuntimeError: Given input size: (256x2x4). Calculated output size: (256x0x1). Output size is too small at /pytorch/aten/src/THNN/generic/SpatialDilatedMaxPooling.c:67

**Comment by thelittlekid** [comment]
The `pil_im.thumbnail((224, 224))` in `preprocess_image` function will resize the input image by keeping the aspect ratio. The examples work because they are square. When the aspect ratio of test images varies, maybe use `pil_im = pil_im.resize((224, 224))` instead.
