### ISSUE TITLE
What does the filter_pos mean in layer_activation_with_guided_backprop.py?

### ISSUE THREAD

**Issue by AndrewSoul** [utkuozbulak/pytorch-cnn-visualizations#48]
Hi, I have a question. What does the filter_pos mean in layer_activation_with_guided_backprop.py? Does it mean the output channel for conv_output?

**Comment by utkuozbulak** [comment]
Hello, 

Sorry for the late reply. It is the position of the filter.

Imagine the convolution output as 32xAxB. This means there are 32 filters with A height and B width. Among these 32 filters, filter_pos selects one.
