### ISSUE TITLE
Code for activation visualisation

### ISSUE THREAD

**Issue by maria8899** [utkuozbulak/pytorch-cnn-visualizations#49]
Hi,
Nice code! For the sake of completeness, I think it would be great to add
-  Simple feature map visualization
- CAM only (no grad) through "Learning Deep Features for Discriminative Localization" (http://cnnlocalization.csail.mit.edu/)
(I think Grad-CAM is this ref  "Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization" not the previous one)
https://arxiv.org/abs/1610.02391

**Comment by utkuozbulak** [comment]
Hey,

The reason I did not bother with CAM was because Grad-Cam is the generalization of CAM. 

Thanks for the heads up on the citations. Will fix.

**Comment by utkuozbulak** [comment]
Here you go: e3be35d

Thanks for the notification.
