### ISSUE TITLE
maximize instead of minimize output for filter visualization?

### ISSUE THREAD

**Issue by zym1010** [utkuozbulak/pytorch-cnn-visualizations#5]
In <https://github.com/utkuozbulak/pytorch-cnn-visualizations/blob/master/src/cnn_layer_visualization.py#L104>, I see that the loss of your filter optimization is the mean value of a feature map. Isn't that the loss should be the negative of this, as we want to make the target filter with a higher output? Thanks.

**Comment by zym1010** [comment]
same problem applies to the deep dream implementation as well.

**Comment by utkuozbulak** [comment]
I think so too. Thats a very bad mistake on my end. Thank you.

**Comment by jiqiujia** [comment]
So it makes me confused. Why minimization leads to good visualization results?

**Comment by zym1010** [comment]
@jiqiujia maybe they are visualizing what neurons don’t like.

**Comment by jiqiujia** [comment]
Incredible

**Comment by utkuozbulak** [comment]
Updated, will also update example images soon
