### ISSUE TITLE
guided_backprop register backward/forward hook seems to consume a lot of GPU memory

### ISSUE THREAD

**Issue by Terahezi** [utkuozbulak/pytorch-cnn-visualizations#53]
Hi, really a great job!
I was trying to get a guided-gradcam visualization of a video. But I found as more images have been read, very soon my server shows CUDA out of memory error. Then I discovered that it is because register_backward/forward_hook consumes a lot of GPU memory. Is there any way I could fix this issue? Thanks in advance!

**Comment by utkuozbulak** [comment]
Hello,

How can it consume a lot of GPU memory? The example implementation in this repository does not even use GPU?

**Comment by Terahezi** [comment]
Sorry, forgot to mention that.
I tried to modify your codes and send both the input and the model to gpu.

**Comment by Terahezi** [comment]
> Hello,
> 
> How can it consume a lot of GPU memory? The example implementation in this repository does not even use GPU?

**Comment by Terahezi** [comment]
> > Hello,
> > How can it consume a lot of GPU memory? The example implementation in this repository does not even use GPU?

**Comment by utkuozbulak** [comment]
Pytorch retains the graph of the gradient . If you are not through with scaling up one input to many inputs the retained gradients eventually blow up. I suspect you are having an issue related to this. My suggestion would be to have a look at online resources on this property of Pytorch and what .zero_grad() does.
