### ISSUE TITLE
how to visual the channels of conv ?

### ISSUE THREAD

**Issue by chenbolinstudent** [utkuozbulak/pytorch-cnn-visualizations#55]
how to visual the channels of conv ? now it is only the conv

**Comment by utkuozbulak** [comment]
It does visualize the channels of conv and not the whole conv. Read the description and the code properly please.

**Comment by chenbolinstudent** [comment]
I mean how to visual the channels of layer with CAM ?

**Comment by utkuozbulak** [comment]
If you mean Grad-CAM, just look at the implementation from gradcam.py. I did not implement pure CAM in this repository. You can follow the paper [2] and implement it yourself.

**Comment by chenbolinstudent** [comment]
then how to visual the channels of layer with heatmap? which .py?

**Comment by chenbolinstudent** [comment]
then how to visual the channels of layer with cam_heatmap? which .py?

**Comment by utkuozbulak** [comment]
Just check misc_functions.py.

**Comment by chenbolinstudent** [comment]
how to select the chahnel of layer ?

**Comment by chenbolinstudent** [comment]
how to select the channel of layer ?

**Comment by utkuozbulak** [comment]
Please put some effort to understand the code. The is commented enough to allow easier understanding.

**Comment by chenbolinstudent** [comment]
![FSV``V4`U~4M_84 P$N~`M7](https://user-images.githubusercontent.com/40932226/64222282-24745a00-cf02-11e9-932e-d9ebd35ec53c.png)


how  to do it ?
please
