### ISSUE TITLE
CAM calculation

### ISSUE THREAD

**Issue by SongweiGe** [utkuozbulak/pytorch-cnn-visualizations#56]
Hi, it seems your implementation of CAM is quite different from the one proposed in the original paper [2]. In [2] the authors modified the model by replacing the fc layers with global average pooling, where new weights are introduced. Here it seems you directly used the sum of the gradient as the weight. Is there any reference for this method? Thanks!

**Comment by utkuozbulak** [comment]
Hey, there is no implementation of CAM in this repository but only Grad-CAM. 

I should correct citation for that one, it was previously mentioned by someone else too.

**Comment by utkuozbulak** [comment]
Here you go: e3be35d

Thanks for the notification.
