### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by ZHuiLBo** [utkuozbulak/pytorch-cnn-visualizations#6]
I ran "python gradcam.py" command in the './src/' directory , and i got the AttributeError: 'NoneType' object has no attribute 'data', how to solve this problem?

![1](https://user-images.githubusercontent.com/28040964/37585172-20b2f99e-2b93-11e8-8993-3c5c59d05d35.jpg)

**Comment by utkuozbulak** [comment]
Hey, I changed the model from VGG to Alexnet a while ago and the target layer in gradcam was left as 35. Since Alexnet doesn't have that many layers it produces the error. Changed the target layer to 11. It should work as now.

**Comment by ZHuiLBo** [comment]
It worked！Thank u very much

**Comment by utkuozbulak** [comment]
Great!
