### ISSUE TITLE
Is Filter Visualization the same thing as Class Specific Image Generation?

### ISSUE THREAD

**Issue by herrickli** [utkuozbulak/pytorch-cnn-visualizations#60]
I haven't find the Filter Visualization module in the code, and as it's seems the same thing as Class Specific Image Generation theoretically. Am I right? Thanks.

**Comment by utkuozbulak** [comment]
Hello, I assume you are talking about layer visualization? (Its in cnn_layer_visualization.py) 

Class specific image generation tries to maximize a class whereas the filter vis. tries to maximize the mean of a filter. Other than that, they are mostly the same.

**Comment by herrickli** [comment]
Hi, I mean this part [Filter Visualization](https://github.com/utkuozbulak/pytorch-cnn-visualizations#convolutional-neural-network-filter-visualization), I haven't find how these pictures are generated in the code.Thanks. @utkuozbulak

**Comment by herrickli** [comment]
Thank you. @utkuozbulak
