### ISSUE TITLE
Question About gradcam.py

### ISSUE THREAD

**Issue by Bear-kai** [utkuozbulak/pytorch-cnn-visualizations#66]
L81: cam=np.ones(target.shape[1:], dtype=np.float32)   # Why not np.zeros()?

**Comment by narrowsnap** [comment]
You can find in #11.

**Comment by Bear-kai** [comment]
@narrowsnap 
Thanks, get it !

**Comment by utkuozbulak** [comment]
Thank you for the answer @narrowsnap !
