### ISSUE TITLE
Functionality requests

### ISSUE THREAD

**Issue by cianeastwood** [utkuozbulak/pytorch-cnn-visualizations#73]
Fantastic repo!

If you had time, would be nice to add the following for completeness:

1. **"Top 9 images" function:** returns top 9 images for a given filter (highest activations), showing them in a 3x3 grid
2. **"Selected channel" function:** spits out an enlarged version of channel activations for a given filter

These functions are depicted in ["Understanding Neural Networks Through Deep Visualization"](https://arxiv.org/pdf/1506.06579.pdf), Figure 1.

They are implemented in Caffe in [Deep Visualisation Toolbox](https://github.com/yosinski/deep-visualization-toolbox), but it would be nice to have them all together in this neat PyTorch repo.

Cheers :)

C

**Comment by cianeastwood** [comment]
nevermind!

**Comment by cianeastwood** [comment]
nevermind!

**Comment by cianeastwood** [comment]
s

**Comment by utkuozbulak** [comment]
Hey @cianeastwood, unfortunately I do not have necessary free time to implement those techniques. Feel free to contribute to the repository though.
