### ISSUE TITLE
Vanilla Gradient as heat map

### ISSUE THREAD

**Issue by uzair-mehmood-storex** [utkuozbulak/pytorch-cnn-visualizations#75]
Great work, I highly appreciate your work and it helps me alot in my reaearch. I have been exploring your techniques and code and want to ask you that, is there any way to render vanilla gradients as heatmap?

**Comment by utkuozbulak** [comment]
Hey, I'm glad it was useful for you.

You can simply pass grayscale values to colormap and get similar heatmaps but if you do it that way, I'm pretty sure it will look jittery (not as smooth grad-cam, quick drops from high to low value and vice versa). Maybe try applying smoothing to the saliency map and then applying colormap. I think that would do it.

**Comment by uzair-mehmood** [comment]
Great, Thanks. Well, can I get heat maps which shows the behavior of gaussian, just like grad cam. Even after smoothing its quite jittery

**Comment by utkuozbulak** [comment]
You can smooth harder with bigger kernels. I personally didn't try smoothing so not sure what kind of stuff you will get.
