### ISSUE TITLE
Support for Score-CAM

### ISSUE THREAD

**Issue by haofanwang** [utkuozbulak/pytorch-cnn-visualizations#76]
Any interest in implementing Score-CAM which is a gradient-free extension of CAM. Here is the [reference code and paper](https://github.com/haofanwang/Score-CAM). It should easy to implement with some modifications on Grad-CAM code.

**Comment by utkuozbulak** [comment]
Hey, it is already implemented in the linked repository, why would it need a another implementation?

**Comment by haofanwang** [comment]
Hi, @utkuozbulak. The original code may not be easy to understand after encapsulation. Your project has implemented many common methods in the same style, others may be able to better compare the differences between this method and different CAM.  I'm willing to implement and PR if it is ok for you.

**Comment by utkuozbulak** [comment]
Hey, I did not realize you were the author, hah. Sure thing, send a PR! I certainly hope it increases the adoption rate of your method!

Can you please format it to be a single python file, you can also use the functions in misc_functions.py if they are any useful. Also, please mention that you are the author in the file. For example, see:
 https://github.com/utkuozbulak/pytorch-cnn-visualizations/blob/master/src/generate_regularized_class_specific_samples.py
