### ISSUE TITLE
Semantic segmentation

### ISSUE THREAD

**Issue by swjtulinxi** [utkuozbulak/pytorch-cnn-visualizations#79]
hi，How to use it to visualize the feature map of semantic segmentations,because i want to  visualize the attention map

**Comment by utkuozbulak** [comment]
Hello,

All examples in this repository concern classification. You can try to adapt them for segmentation, although I do not know how successful it will be.

**Comment by abhigoku10** [comment]
@utkuozbulak  can you provide references for modifications of the current implementation to obtain segmentation cams

**Comment by utkuozbulak** [comment]
Hey, I'm not aware of any segmentation methods in particular that use any visualization approaches. (Can you link here if you find any?)
