### ISSUE TITLE
Gam-Cam Accumulator

### ISSUE THREAD

**Issue by richardtml** [utkuozbulak/pytorch-cnn-visualizations#81]
Hi, thank you for the implementations. 

There is a line (81) in Gram-Cam I suspect incorrectly amplifies the intensities of the cam map:

```
cam = np.ones(target.shape[1:], dtype=np.float32)
```

According to the paper there's no sum +1, so this change the appearance in the final maps. I think the accumulator should be zero:

```
cam = np.zeros(target.shape[1:], dtype=np.float32)
```

Is this correct?

Thank you!

**Comment by utkuozbulak** [comment]
Hey,

You can have a look at a relevant discussion here: #11.

**Comment by richardtml** [comment]
Interesting, thank you!
