### ISSUE TITLE
Class correctness in gradcam.py

### ISSUE THREAD

**Issue by AND2797** [utkuozbulak/pytorch-cnn-visualizations#85]
There is a [line](https://github.com/utkuozbulak/pytorch-cnn-visualizations/blob/7dd09a0fc04abcd2a4a3ddb47b8ea230732b8a94/src/gradcam.py#L64) in gradcam.py which says that if `target_class = None` then the `target_class` takes the argmax of the ouptut. Is it possible that the actual class might be different from the expected class?

**Comment by utkuozbulak** [comment]
If it is a misclassification and the true class is not provided, yeah.

**Comment by AND2797** [comment]
So in this case would it be appropriate to raise an assertion error? For eg: I input class 5, but the model output indicates that the image is classified as class 4, which would be incorrect

**Comment by utkuozbulak** [comment]
If you enter a target class then target class would not be None.

**Comment by AND2797** [comment]
No what I mean is this ->

1. User enters `target_class` = `5`, and image corresponding to `target_class` = `5`.
2. Output of `torch.argmax(model_output).item()` is not `5`, then in this case it means that the model has incorrectly classified the image, so will it not give incorrect results?

**Comment by utkuozbulak** [comment]
If the user enters `target_class` = `5`, then the target_class is not None and what is inside the if condition will not be executed.

**Comment by AND2797** [comment]
I am a little confused, can you explain what happens if the true class is given and a mis-classification occurs?

**Comment by utkuozbulak** [comment]
Please read the code. If the target_class is not provided, it is taken from the prediction. When the target_class is provided, what comes out of the prediction is not used. So, there is no case when the user provides a class (e.g., 5) and the target_class magically changes to 44.

**Comment by AND2797** [comment]
Thanks for the clarification.
