### ISSUE TITLE
Forward pass not using the avgpool()

### ISSUE THREAD

**Issue by viniciusarruda** [utkuozbulak/pytorch-cnn-visualizations#86]
Hi, at the `forward_pass()` functions, as in `gradcam.py`, the `self.model.avgpool` is not used. Why?
At `misc_functions.py`, after loading the AlexNet model, you can print it and see that it is there, but didn't see any usage of it in the code.

**Comment by utkuozbulak** [comment]
Hey,

Yeah, should be there. Feel free to send a pr.

**Comment by viniciusarruda** [comment]
Sorry, I was using a more recent version of PyTorch. I found that previous versions do not have the avgpool.

**Comment by utkuozbulak** [comment]
Aha. You are right again. Thanks for the heads up.

![image](https://user-images.githubusercontent.com/19213588/91996667-39cdcf80-ed74-11ea-8336-dc1ba499284d.png)
