### ISSUE TITLE
too many indices for array

### ISSUE THREAD

**Issue by shashanka300** [utkuozbulak/pytorch-cnn-visualizations#9]
Traceback (most recent call last):
  File "X:/pytorch-cnn-visualizations-master/src/cnn_layer_visualization.py", line 130, in <module>
    layer_vis.visualise_layer_without_hooks()
  File "X:/pytorch-cnn-visualizations-master/src/cnn_layer_visualization.py", line 105, in visualise_layer_without_hooks
    print('Iteration:', str(i), 'Loss:', "{0:.2f}".format(loss.data.numpy()[0]))
IndexError: too many indices for array
same Error in deep_dreem.py in exactly the same line but lint no 62,
same in inverted_representation.py line 106 and generate_claass_specificsamples.py line 43

**Comment by utkuozbulak** [comment]
Thanks for the notice! I will have a look at it as soon as I can.

**Comment by shashanka300** [comment]
0.4.0 on windows

**Comment by utkuozbulak** [comment]
I'm still using 0.2.0.post4, maybe it is time to upgrade as well. I will have a look on this in the upcoming day and perhaps overhaul all of the files.

**Comment by giddyyupp** [comment]
just remove "[0]" from that lines.

**Comment by utkuozbulak** [comment]
Then it will not work for me, you have to understand that there are more code that I work with (apart from this repository) that is integrated together. I will not make such changes before I myself change the version that I built everything on.

I will keep this issue open in case people have the same issue, they can see how to fix it.

**Comment by giddyyupp** [comment]
yes of course, i directed it to who have this error :D

**Comment by utkuozbulak** [comment]
Updated the code for pytorch v0.4 compatibility.
