### ISSUE TITLE
Score-CAM: 'ResNet' object has no attribute 'features'

### ISSUE THREAD

**Issue by chuanenlin** [utkuozbulak/pytorch-cnn-visualizations#90]
In `scorecam.py`, the code gets the model features using `model.features` (line 28).

This works for architectures like AlexNet and VGG, but doesn't work for WideResNet or ResNet with the error message: `'ResNet' object has no attribute 'features'`

Any idea how to run Score-CAM for a pre-trained WideResNet model?

**Comment by utkuozbulak** [comment]
Hey,

You can see relevant discussion for models that don't contain convolutions in a 'features' sequential module here: https://github.com/utkuozbulak/pytorch-cnn-visualizations/issues/82
