### ISSUE TITLE
Score-CAM ResNet Support

### ISSUE THREAD

**Issue by dimimal** [utkuozbulak/pytorch-cnn-visualizations#93]
Hi, 

Just a quick question, I noticed that Sore-CAM is implemented in a way that supports only ALexNet. In order to support other pretrained models like Resnet, should I change the forwad_convolutions function and extract the last conv layer before pooling or should I change anything else?

**Comment by haofanwang** [comment]
@dimimal Yes, as the network structures are different, you need to extract the feature map of ResNet by modifying several lines of code. Here are some [references](https://github.com/haofanwang/Score-CAM/blob/master/cam/basecam.py) that may be helpful to you.
