### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by omzoughi** [utkuozbulak/pytorch-cnn-visualizations#95]
Hello,

I am reading your code: generate_class_specific_samples.py, line:  output = self.model(self.processed_image).

My question is technical. Here, the class instantiation  self is of type class 'torchvision.models.alexnet.AlexNet'. By which property you redefined the class attribute model ? Is there any python property which tolerate the redefinition of the constructor?

Thank you for your answer.

**Comment by utkuozbulak** [comment]
Hello, check what comes from misc_functions.py.
